version: '3.7'
services:
  app1:
    container_name: app1
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8001:8000"
    volumes:
      - .:/usr/src/app
  app2:
    container_name: app2
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8002:8000"
    volumes:
      - .:/usr/src/app
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - "8080:8080"
    depends_on:
      - app1
      - app2


